import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";
import Card from "../components/card";
import axios from "axios";
import useTrackLocation from "../hooks/track-location";
import { fetchCoffeeStores } from "../lib/coffee-store";
import { useEffect, useState } from "react";

export async function getStaticProps(context) {
  const coffeeStoresData = await fetchCoffeeStores();

  // const config = {
  //   method: "get",
  //   url: "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=cafe&keyword=cruise&key=AIzaSyDrkGbo8W8P7XwpJ45ZwRU--uFrckGtxqQ",
  //   headers: {},
  // };
  // const response = await axios(config)
  //   .then(function (response) {
  //     console.log(response.data);
  //     return response.data;
  //   })
  //   .catch(function (error) {
  //     console.log(error);
  //   });

  // const config = {
  //   method: "get",
  //   headers: {},
  // };

  // const response = await fetch(
  //   "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=restaurant&keyword=cruise&key=AIzaSyDrkGbo8W8P7XwpJ45ZwRU--uFrckGtxqQ",
  //   config
  // );
  // const data = await response.json();
  return {
    props: {
      coffeeStores: coffeeStoresData.slice(0, 6),
    },
  };
}
// export async function getStaticProps(context) {
//   // const coffeeStores = await fetchCoffeeStores();
//   const options = {
//     method: "GET",
//     headers: {
//       Accept: "application/json",
//       // "User-Agent": "*",
//       Authorization: "fsq3FXaSn50EuIRHwsY56goX3XOQK7AQkJXo/MElJz0WJyY=",
//     },
//   };

//   const response = await fetch(
//     `https://api.foursquare.com/v3/places/search?query=coffee&ll=43.653833032607096%2C-79.37896808855945&limit=6`,
//     options
//   );

//   const data = await response.json();
//   console.log("data", data);
//   return {
//     props: {
//       coffeeStores: data.results,
//     },
//   };
// }

export default function Home(props) {
  const [nearbyStores, setNearbyStores] = useState([]);
  const [coffeeStoreError, setCoffeeStoreError] = useState(null);
  console.log(props);
  const { latLong, handleTrackLocation, locationErrorMsg, isFindingLocation } =
    useTrackLocation();

  console.log({ latLong, locationErrorMsg });

  useEffect(() => {
    async function setCoffeeStoresByLocation() {
      if (latLong) {
        try {
          const fetchedCoffeeStores = await fetchCoffeeStores(latLong);
          setNearbyStores(fetchedCoffeeStores);
          console.log({ fetchedCoffeeStores });
        } catch (error) {
          console.log("Error", { error });
          setCoffeeStoreError(error.message);
        }
      }
    }
    setCoffeeStoresByLocation();
  }, [latLong]);

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coffee.svg" />
      </Head>
      <main className={styles.main}>
        <Banner
          handleOnClick={handleOnBannerBtnClick}
          buttonText={isFindingLocation ? "Loading..." : "View stores nearby"}
        />
        {locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
        {coffeeStoreError && <p>Something went wrong: {coffeeStoreError}</p>}
        <div className={styles.heroImage}>
          <Image src="/static/hero.png" width={700} height={400} />
        </div>
        {nearbyStores.length > 0 && (
          <h2 className={styles.heading2}>Nearby Stores</h2>
        )}
        {nearbyStores.length > 0 && (
          <>
            <div className={styles.cardLayout}>
              {nearbyStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore?.imgUrl || "/static/hero.png"}
                    href={`/coffee/${coffeeStore?.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
        <h2 className={styles.heading2}>Toronto stores</h2>
        {props.coffeeStores.length > 0 && (
          <>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore?.imgUrl || "/static/hero.png"}
                    href={`/coffee/${coffeeStore?.id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
