import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";
import Card from "../components/card";
import axios from "axios";

import { fetchCoffeeStores } from "../lib/coffee-store";

export async function getStaticProps(context) {
  const coffeeStoresData = await fetchCoffeeStores();

  // const config = {
  //   method: "get",
  //   url: "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=cafe&keyword=cruise&key=AIzaSyDrkGbo8W8P7XwpJ45ZwRU--uFrckGtxqQ",
  //   headers: {},
  // };
  // const response = await axios(config)
  //   .then(function (response) {
  //     console.log(response.data);
  //     return response.data;
  //   })
  //   .catch(function (error) {
  //     console.log(error);
  //   });

  // const config = {
  //   method: "get",
  //   headers: {},
  // };

  // const response = await fetch(
  //   "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=restaurant&keyword=cruise&key=AIzaSyDrkGbo8W8P7XwpJ45ZwRU--uFrckGtxqQ",
  //   config
  // );
  // const data = await response.json();
  return {
    props: {
      coffeeStores: coffeeStoresData.slice(0, 6),
    },
  };
}
// export async function getStaticProps(context) {
//   // const coffeeStores = await fetchCoffeeStores();
//   const options = {
//     method: "GET",
//     headers: {
//       Accept: "application/json",
//       // "User-Agent": "*",
//       Authorization: "fsq3FXaSn50EuIRHwsY56goX3XOQK7AQkJXo/MElJz0WJyY=",
//     },
//   };

//   const response = await fetch(
//     `https://api.foursquare.com/v3/places/search?query=coffee&ll=43.653833032607096%2C-79.37896808855945&limit=6`,
//     options
//   );

//   const data = await response.json();
//   console.log("data", data);
//   return {
//     props: {
//       coffeeStores: data.results,
//     },
//   };
// }

export default function Home(props) {
  console.log(props);

  const handleOnBannerBtnClick = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/coffee.svg" />
      </Head>
      <main className={styles.main}>
        <Banner
          handleOnClick={handleOnBannerBtnClick}
          buttonText="View stores nearby"
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero.png" width={700} height={400} />
        </div>
        <h2 className={styles.heading2}>Toronto stores</h2>
        {props.coffeeStores.length > 0 && (
          <>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.place_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore?.imgUrl || "/static/hero.png"}
                    href={`/coffee/${coffeeStore?.place_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
